-- BuldacityOS_Tier3.lua
-- BULDACITY OS // Tier-3 OpenComputers Desktop
-- Minecraft 1.7.10 / OpenComputers
-- One central BULDACITY server. Normal controller PCs are clients.

local component=require("component")
local event=require("event")
local computer=require("computer")
local filesystem=require("filesystem")
local network=require("Network")
local gpu=component.gpu
local PROTOCOL="BULDACITY/2"
local PORT=4242
local VERSION="5.0"
local ok,mode=network.startServer()
if not ok then error("BULDACITY OS: modem/network card required") end
local W,H=gpu.getResolution();local running=true;local page="HOME";local selected=1;local appSelected=1;local driveSelected=1
local devices={};local logs={};local frames={};local frameSize={};local status="ONLINE";local lastInput=0;local lastFrame=0;local dirty=true
local C={bg=0x050811,bar=0x0B1220,panel=0x101A2C,panel2=0x172640,line=0x263B59,cyan=0x00E5FF,purple=0xA66CFF,pink=0xFF3EBB,green=0x35F59A,yellow=0xFFD34E,red=0xFF5572,white=0xEAF6FF,dim=0x71859E,black=0x000000,orange=0xFF9D45}
local function now() return computer.uptime() end
local function fit(s,n) s=tostring(s or "");n=math.max(1,n or 1);if #s<=n then return s end;if n==1 then return s:sub(1,1) end;return s:sub(1,n-1).."…" end
local function text(x,y,s,c,bg) if x<1 or y<1 or x>W or y>H then return end;gpu.setForeground(c or C.white);gpu.setBackground(bg or C.bg);gpu.set(x,y,tostring(s or "")) end
local function fill(x,y,w,h,c) if x<=W and y<=H and w>0 and h>0 then gpu.setBackground(c);gpu.fill(x,y,math.min(w,W-x+1),math.min(h,H-y+1)," ") end end
local function rule(x,y,w,c) if w>0 then fill(x,y,w,1,c or C.line) end end
local function log(s) table.insert(logs,1,os.date("%H:%M:%S").."  "..tostring(s));if #logs>14 then table.remove(logs) end end
local function panel(x,y,w,h,title,c) fill(x,y,w,h,C.panel);fill(x,y,w,1,c or C.cyan);text(x+2,y+2,"◆ "..fit(title,w-6),c or C.cyan,C.panel);rule(x+2,y+3,w-4,C.line) end
local function online(d) return d and now()-(d.last or 0)<12 end
local function deviceList() local r={};for _,d in pairs(devices) do r[#r+1]=d end;table.sort(r,function(a,b)return tostring(a.name or a.address)<tostring(b.name or b.address) end);return r end
local function selectedDevice() local l=deviceList();if #l==0 then return nil end;selected=math.max(1,math.min(selected,#l));return l[selected] end
local function send(d,k,data) if d and online(d) then return network.send(d.address,k,data) end;return false end
local function hello() network.broadcast("SERVER_HELLO",{name="BULDACITY TIER-3",role="SERVER",app="BULDACITY OS",version=VERSION,protocol=PROTOCOL,port=PORT}) end
local function scan() hello();for _,d in ipairs(deviceList()) do if online(d) then send(d,"PING",{from="TIER3"}) end end;status="SCAN SENT";log("Network discovery broadcast");dirty=true end
local function requestScreen(d) if d then send(d,"SCREEN_REQUEST",{width=W,height=H}) end end
local function fmtBytes(n) n=tonumber(n) or 0;if n>=1073741824 then return string.format("%.1f GB",n/1073741824) end;if n>=1048576 then return string.format("%.1f MB",n/1048576) end;if n>=1024 then return string.format("%.1f KB",n/1024) end;return string.format("%d B",n) end
local function drives() local r={};local it=filesystem.mounts();if it then while true do local fs,path=it();if not fs then break end;local total=0;local used=0;pcall(function() total=fs.spaceTotal() or 0 end);pcall(function() used=fs.spaceUsed() or 0 end);local label="";pcall(function() label=fs.getLabel() or "" end);r[#r+1]={fs=fs,path=path,total=total,used=used,label=label} end end;return r end
local function driveInfo(d) if not d then return 0,0,0 end;local total=tonumber(d.total) or 0;local used=tonumber(d.used) or 0;if total<=0 then pcall(function() total=d.fs.spaceTotal() or 0 end) end;if used<=0 then pcall(function() used=d.fs.spaceUsed() or 0 end) end;local pct=total>0 and math.max(0,math.min(100,used/total*100)) or 0;return total,used,pct end
local function gauge(x,y,w,label,value,maxValue,unit,c) value=tonumber(value) or 0;maxValue=tonumber(maxValue) or 100;local pct=maxValue>0 and math.max(0,math.min(1,value/maxValue)) or 0;text(x,y,label,C.dim);text(x+w-10,y,string.format("%5.1f%s",value,unit or ""),c or C.white);fill(x,y+1,w,2,C.bar);fill(x,y+1,math.max(1,math.floor(w*pct)),2,c or C.cyan) end
local function header(title,sub) fill(1,1,W,5,C.bar);fill(1,5,W,1,C.cyan);text(3,2,"BULDACITY",C.cyan,C.bar);text(14,2,"OS",C.white,C.bar);text(18,2,title,C.purple,C.bar);text(3,3,sub or "TIER-3 CENTRAL CONTROL",C.dim,C.bar);text(math.max(1,W-25),2,"● NETWORK ONLINE",C.green,C.bar);text(math.max(1,W-14),3,PROTOCOL,C.cyan,C.bar);text(math.max(1,W-8),4,os.date("%H:%M"),C.white,C.bar) end
local function nav() local n={{"1","HOME"},{"2","NETWORK"},{"3","DEVICES"},{"4","APPS"},{"5","DISKS"},{"6","REMOTE"},{"7","SYSTEM"}};local x=2;fill(1,H-3,W,4,C.bar);for _,v in ipairs(n) do local active=page==v[2];text(x,H-1,"["..v[1].."] "..v[2],active and C.white or C.dim,C.bar);x=x+11 end;text(math.max(1,W-18),H-1,fit(status,15),C.green,C.bar);text(math.max(1,W-3),H-1,"Q",C.red,C.bar) end
local function home() header("HOME","CENTRAL CONTROL // REAL PC STYLE DESKTOP");local l=deviceList();local up=0;for _,d in ipairs(l) do if online(d) then up=up+1 end end;panel(3,7,23,9,"NETWORK",C.cyan);text(6,10,"STATUS",C.dim);text(15,10,"ONLINE",C.green);text(6,12,"PORT",C.dim);text(15,12,PORT,C.yellow);text(6,14,"CLIENTS",C.dim);text(15,14,up.." / "..#l,C.cyan);text(6,16,"MODE",C.dim);text(15,16,fit(mode,9),C.green);panel(28,7,23,9,"COMPUTER",C.purple);text(31,10,"TIER",C.dim);text(41,10,"TIER-3",C.cyan);text(31,12,"UPTIME",C.dim);text(41,12,string.format("%.0fs",computer.uptime()),C.white);text(31,14,"ENERGY",C.dim);text(41,14,computer.energy and math.floor(computer.energy()) or "N/A",C.green);text(31,16,"VERSION",C.dim);text(41,16,VERSION,C.white);panel(53,7,25,9,"QUICK APPS",C.pink);text(57,10,"[4]",C.cyan);text(62,10,"APP LIBRARY",C.white);text(57,12,"[5]",C.cyan);text(62,12,"DISK MANAGER",C.white);text(57,14,"[6]",C.cyan);text(62,14,"REMOTE PC",C.white);text(57,16,"[R]",C.cyan);text(62,16,"NETWORK SCAN",C.white);panel(3,18,75,10,"LIVE FLEET",C.green);if #l==0 then text(7,23,"Waiting for normal Tier-3 controller PCs...",C.dim) end;for i,d in ipairs(l) do if i>6 then break end;local y=19+i;text(7,y,string.format("%02d",i),C.dim);text(12,y,fit(d.name or "CONTROLLER",24),C.white);text(39,y,fit(d.controller or d.app or "NETWORK CLIENT",18),C.dim);text(61,y,online(d) and "● ONLINE" or "○ OFFLINE",online(d) and C.green or C.red) end;panel(3,30,75,math.max(4,H-33),"SYSTEM LOG",C.yellow);for i=1,math.min(#logs,H-36) do text(6,30+i,fit(logs[i],W-10),C.dim) end;nav() end
local function networkPage() header("NETWORK","BULDACITY/2 // CENTRAL SERVER + NORMAL CLIENT PCS");panel(3,7,75,9,"NETWORK CORE",C.cyan);text(7,10,"ROLE",C.dim);text(19,10,"CENTRAL SERVER",C.green);text(7,12,"PROTOCOL",C.dim);text(19,12,PROTOCOL,C.cyan);text(7,14,"PORT",C.dim);text(19,14,PORT,C.yellow);text(40,10,"ADDRESS",C.dim);text(52,10,fit(network.address(),24),C.white);text(40,12,"CLIENT MODE",C.dim);text(52,12,"NORMAL TIER-3 PCs",C.green);text(40,14,"ACCESS CONTROL",C.dim);text(52,14,"NONE",C.orange);panel(3,17,75,math.max(7,H-21),"HEARTBEAT / LINK MONITOR",C.purple);local l=deviceList();for i,d in ipairs(l) do local y=18+i;if y>H-5 then break end;text(7,y,string.format("%02d",i),C.dim);text(12,y,fit(d.name or "UNKNOWN",23),C.white);text(37,y,fit(d.address or "",14),C.dim);text(53,y,online(d) and "ONLINE" or "OFFLINE",online(d) and C.green or C.red);text(65,y,online(d) and string.format("%02ds",math.floor(now()-(d.last or now()))) or "--",C.dim) end;text(7,H-5,"R = rediscover   3 = devices   6 = remote",C.dim);nav() end
local function devicesPage() header("DEVICES","CONTROLLER FLEET // NORMAL OPENCOMPUTERS CLIENTS");panel(3,7,48,H-11,"CONNECTED CONTROLLERS",C.purple);local l=deviceList();if #l==0 then text(7,12,"No network controller is online.",C.dim);text(7,14,"Start one of the *Network*.lua client programs.",C.dim) end;for i,d in ipairs(l) do local y=9+i;if y>H-6 then break end;if i==selected then fill(5,y,44,1,C.panel2);fill(5,y,2,1,C.cyan) end;text(8,y,string.format("%02d",i),C.dim);text(13,y,fit(d.name or "UNKNOWN",20),i==selected and C.cyan or C.white);text(35,y,online(d) and "● ONLINE" or "○ OFFLINE",online(d) and C.green or C.red) end;local d=selectedDevice();panel(53,7,25,H-11,"SELECTED CLIENT",C.cyan);if d then text(57,11,"NAME",C.dim);text(57,12,fit(d.name,17),C.white);text(57,15,"APP",C.dim);text(57,16,fit(d.controller or d.app or "CLIENT",17),C.purple);text(57,19,"ADDRESS",C.dim);text(57,20,fit(d.address,17),C.white);text(57,23,"DISTANCE",C.dim);text(57,24,tostring(d.distance or "--"),C.yellow);text(57,27,"STATUS",C.dim);text(57,28,online(d) and "ONLINE" or "OFFLINE",online(d) and C.green or C.red);text(57,31,"ENTER",C.cyan);text(64,31,"REMOTE",C.white) else text(57,13,"Select a client.",C.dim) end;text(7,H-5,"↑/↓ or W/S select   ENTER = remote   R = scan",C.dim);nav() end
local function appFiles() local files={};for f in filesystem.list("/") do f=f:gsub("/$","");if f:match("_Modern%.lua$") or f=="ReactorBigReactors043A_Touch_Responsive.lua" then files[#files+1]=f end end;table.sort(files);return files end
local function appsPage() header("APPS","APPLICATION LIBRARY // MODERN LOCAL CONTROLLERS");panel(3,7,75,H-11,"DESKTOP APPLICATIONS",C.pink);local files=appFiles();appSelected=math.max(1,math.min(appSelected,math.max(1,#files)));if #files==0 then text(7,12,"No local controller applications found.",C.dim) end;for i,f in ipairs(files) do local y=8+i;if y>H-8 then break end;local active=i==appSelected;if active then fill(5,y,70,1,C.panel2);fill(5,y,2,1,C.pink) end;text(8,y,string.format("%02d",i),C.dim);text(12,y,fit(f,53),active and C.white or C.dim);text(68,y,"LOCAL",C.green) end;text(7,H-5,"↑/↓ select   ENTER = launch local Modern controller",C.dim);nav() end
local function disksPage() header("DISKS","REAL STORAGE DEVICES // CAPACITY + USED + FREE");panel(3,7,75,H-11,"STORAGE DEVICES",C.cyan);local l=drives();driveSelected=math.max(1,math.min(driveSelected,math.max(1,#l)));if #l==0 then text(7,12,"No mounted filesystem devices detected.",C.dim) end;for i,d in ipairs(l) do local y=8+i;if y>H-8 then break end;local total,used,pct=driveInfo(d);local active=i==driveSelected;if active then fill(5,y,70,1,C.panel2) end;text(8,y,string.format("%02d",i),C.dim);text(12,y,fit((d.label~="" and d.label or d.path or "DISK"),22),active and C.cyan or C.white);text(36,y,fmtBytes(used).." / "..fmtBytes(total),C.white);text(58,y,string.format("%5.1f%%",pct),pct>90 and C.red or C.green);local ro=false;pcall(function() ro=d.fs.isReadOnly() end);text(68,y,ro and "RO" or "RW",C.dim) end;local d=l[driveSelected];if d then local total,used,pct=driveInfo(d);local free=math.max(0,total-used);text(7,H-5,"SELECTED",C.dim);text(17,H-5,fit(d.path or "DISK",18),C.white);text(38,H-5,"USED",C.dim);text(44,H-5,fmtBytes(used),C.yellow);text(57,H-5,"FREE",C.dim);text(63,H-5,fmtBytes(free),C.green) end;nav() end
local function remotePage() header("REMOTE","LIVE REMOTE PC // SCREEN + KEYBOARD + TOUCH + SCROLL");local d=selectedDevice();if not d then panel(3,7,75,H-11,"REMOTE DESKTOP",C.pink);text(7,12,"No controller selected.",C.dim);text(7,14,"Open DEVICES and select a normal Tier-3 controller PC.",C.dim);nav();return end;local frame=frames[d.address];local sz=frameSize[d.address] or {w=0,h=0};local ox,oy=3,7;local vw=math.min(math.max(10,W-6),sz.w>0 and sz.w or W-6);local vh=math.min(math.max(8,H-12),sz.h>0 and sz.h or H-12);fill(ox,oy,vw+2,vh+3,C.panel);fill(ox,oy,vw+2,1,C.pink);text(ox+2,oy+2,fit(d.name or "CONTROLLER",vw-4),C.white,C.panel);rule(ox+2,oy+3,vw-2,C.line);if frame then for y=1,math.min(vh-3,sz.h) do local row=frame[y];if row then for x=1,math.min(vw,sz.w) do local cell=row[x];if cell then gpu.setBackground(cell[3] or C.black);gpu.setForeground(cell[2] or C.white);gpu.set(ox+x,oy+3+y,cell[1] or " ") end end end end else text(ox+4,oy+8,"WAITING FOR REMOTE SCREEN...",C.dim) end;fill(ox,oy+vh+1,vw+2,2,C.bar);text(ox+2,oy+vh+2,"LIVE | ENTER=PING | R=REFRESH | ESC=DEVICES | CLICK=TOUCH",C.dim,C.bar);nav() end
local function systemPage() header("SYSTEM","TIER-3 DIAGNOSTICS // REAL METRICS");panel(3,7,36,13,"COMPUTER",C.yellow);text(7,10,"UPTIME",C.dim);text(19,10,string.format("%.1fs",computer.uptime()),C.white);text(7,12,"ENERGY",C.dim);text(19,12,computer.energy and math.floor(computer.energy()) or "N/A",C.green);text(7,14,"MAX ENERGY",C.dim);text(19,14,computer.maxEnergy and math.floor(computer.maxEnergy()) or "N/A",C.white);text(7,16,"TIER",C.dim);text(19,16,"TIER-3",C.cyan);text(7,18,"NETWORK",C.dim);text(19,18,"CENTRAL SERVER",C.green);panel(41,7,37,13,"LIVE GAUGES",C.cyan);gauge(45,10,29,"CPU ENERGY",computer.energy and computer.energy() or 0,computer.maxEnergy and computer.maxEnergy() or 1,"",C.green);gauge(45,14,29,"NETWORK CLIENTS",#deviceList(),math.max(1,#deviceList()),"",C.cyan);local dl=drives()[1];local dt,du,dp=driveInfo(dl);gauge(45,18,29,"DISK USED",dp,100,"%",C.purple);panel(3,22,75,H-26,"ARCHITECTURE",C.purple);text(7,25,"CENTRAL",C.dim);text(20,25,"BuldacityOS_Tier3.lua + Network.lua",C.white);text(7,27,"NORMAL PCs",C.dim);text(20,27,"All *Network*.lua controllers are clients",C.green);text(7,29,"MODERN APPS",C.dim);text(20,29,"*_Modern.lua stay as local controller applications",C.purple);text(7,31,"REMOTE",C.dim);text(20,31,"Full character screen + keyboard + touch + scroll",C.cyan);text(7,33,"SECURITY",C.dim);text(20,33,"No whitelist / UUID access-control layer",C.orange);nav() end
local function draw() W,H=gpu.getResolution();gpu.setBackground(C.bg);gpu.fill(1,1,W,H," ");if page=="HOME" then home() elseif page=="NETWORK" then networkPage() elseif page=="DEVICES" then devicesPage() elseif page=="APPS" then appsPage() elseif page=="DISKS" then disksPage() elseif page=="REMOTE" then remotePage() else systemPage() end;dirty=false end
local function remember(sender,p,distance) local data=p.data or {};local d=devices[sender] or {address=sender};devices[sender]=d;for k,v in pairs(data) do d[k]=v end;d.address=sender;d.last=now();d.distance=distance;dirty=true end
local function input(d,eventName,a,b,c) if d then network.send(d.address,"INPUT",{event=eventName,x=a,y=b,char=a,code=b,button=c}) end end
network.startServer(function(sender,p,distance) if p.kind=="HELLO" or p.kind=="HEARTBEAT" then remember(sender,p,distance);status="CLIENT ONLINE";return end;if p.kind=="PONG" then remember(sender,p,distance);return end;if p.kind=="SCREEN_BEGIN" then local s=p.data or {};frameSize[sender]={w=tonumber(s.width) or W,h=tonumber(s.height) or H};frames[sender]={};dirty=true;return end;if p.kind=="SCREEN_ROW" then local s=p.data or {};if frames[sender] and s.y then frames[sender][s.y]=s.cells end;dirty=true;return end;if p.kind=="SCREEN_END" then local d=devices[sender];if d then d.last=now();d.screen=now() end;lastFrame=now();dirty=true;return end end)
log("BULDACITY OS "..VERSION.." started");log("Central Tier-3 server on BULDACITY/2 port "..PORT);log("Normal controller PCs are network clients");hello();event.timer(3,hello,math.huge);event.timer(5,scan,math.huge);event.timer(1,function() if page=="REMOTE" then requestScreen(selectedDevice()) end end,math.huge);event.timer(1,function() if dirty then draw() end end,math.huge);draw()
while running do
 local e,a,b,c,d,e2=event.pull(0.20)
 if e=="key_down" or e=="key_up" then
  local char=b or 0;local code=c or 0;local target=selectedDevice()
  if e=="key_down" and (char==113 or char==81) then running=false
  elseif e=="key_down" and char==49 then page="HOME";draw() elseif e=="key_down" and char==50 then page="NETWORK";draw() elseif e=="key_down" and char==51 then page="DEVICES";draw() elseif e=="key_down" and char==52 then page="APPS";draw() elseif e=="key_down" and char==53 then page="DISKS";draw() elseif e=="key_down" and char==54 then page="REMOTE";requestScreen(target);draw() elseif e=="key_down" and char==55 then page="SYSTEM";draw()
  elseif e=="key_down" and (char==114 or char==82) then scan();draw()
  elseif e=="key_down" and (char==119 or code==200) then if page=="DEVICES" then selected=math.max(1,selected-1) elseif page=="APPS" then appSelected=math.max(1,appSelected-1) elseif page=="DISKS" then driveSelected=math.max(1,driveSelected-1) end;draw()
  elseif e=="key_down" and (char==115 or code==208) then if page=="DEVICES" then selected=selected+1 elseif page=="APPS" then appSelected=appSelected+1 elseif page=="DISKS" then driveSelected=driveSelected+1 end;draw()
  elseif e=="key_down" and (code==28 or code==57) then if page=="DEVICES" and target then page="REMOTE";requestScreen(target);draw() elseif page=="REMOTE" and target then send(target,"PING",{from="REMOTE"}) elseif page=="APPS" then local files=appFiles();local f=files[appSelected];if f then log("Launching "..f);os.execute(f);draw() end end
  elseif e=="key_down" and char==27 then page="DEVICES";draw()
  elseif page=="REMOTE" and target and now()-lastInput>0.03 then input(target,e,char,code);lastInput=now() end
 elseif e=="touch" then
  local x,y,button=b,c,d;local target=selectedDevice()
  if page=="DEVICES" then local idx=y-9;if idx>=1 and idx<=#deviceList() then selected=idx;draw() end
  elseif page=="REMOTE" and target then local sz=frameSize[target.address] or {w=W,h=H};local rx=math.max(1,math.min(sz.w,x-4));local ry=math.max(1,math.min(sz.h,y-10));input(target,"touch",rx,ry,button);lastInput=now() end
 elseif e=="scroll" then
  local target=selectedDevice();if page=="DEVICES" then if b>0 then selected=selected-1 else selected=selected+1 end;draw() elseif page=="APPS" then if b>0 then appSelected=appSelected-1 else appSelected=appSelected+1 end;draw() elseif page=="DISKS" then if b>0 then driveSelected=driveSelected-1 else driveSelected=driveSelected+1 end;draw() elseif page=="REMOTE" and target then input(target,"scroll",b,c,d);lastInput=now() end
 end
 if now()-lastInput>0.5 then status="ONLINE" end
end
