-- DieselGenerator_Modern.lua
-- Modern responsive LED dashboard for Immersive Engineering 0.7.7 / OC 1.8.10 / MC 1.7.10
local component=require("component")
local event=require("event")
local computer=require("computer")
local gpu=component.gpu
local gen=component.ie_diesel_generator
if not gen then error("Kein ie_diesel_generator gefunden.") end
local W,H=80,25;local running=true;local mode="AUTO";local enabled=false;local active=false;local amount=0;local capacity=0;local fluid="--";local msg="SYSTEM READY";local ui={};local low=10;local high=20
local C={bg=0x05080D,panel=0x0D141D,panel2=0x111D29,line=0x26384A,blue=0x35B9FF,cyan=0x55F5FF,green=0x39FF88,red=0xFF4F68,yellow=0xFFE36E,orange=0xFF9F43,purple=0xB47CFF,white=0xF4FAFF,grey=0x7F95A8,off=0x24313C}
local function resize()local mw,mh=gpu.maxResolution();local cw,ch=gpu.getResolution();W,H=mw or cw,mh or ch;if W<40 then W=40 end;if H<16 then H=16 end;pcall(gpu.setResolution,W,H);W,H=gpu.getResolution()end
local function sc(fn,...)local ok,a,b,c=pcall(fn,...);if ok then return a,b,c end end
local function txt(x,y,s,fg,bg)gpu.setForeground(fg or C.white);gpu.setBackground(bg or C.bg);gpu.set(x,y,tostring(s))end
local function fit(s,n)s=tostring(s or "");return #s<=n and s or s:sub(1,math.max(1,n-1)).."…"end
local function box(x,y,w,h,t,c)gpu.setBackground(C.panel);gpu.fill(x,y,w,h," ");gpu.setBackground(C.line);gpu.fill(x,y,w,1," ");txt(x+2,y,"◆ "..fit(t,w-5),c or C.cyan,C.panel)end
local function led(x,y,on,c,label)local cc=on and c or C.off;gpu.setBackground(cc);gpu.fill(x,y,2,1," ");txt(x+3,y,fit(label or "STATUS",18),on and cc or C.grey,C.panel)end
local function bar(x,y,w,p,c)p=math.max(0,math.min(100,tonumber(p)or 0));local n=math.floor(w*p/100);gpu.setBackground(C.panel2);gpu.fill(x,y,w,1," ");if n>0 then gpu.setBackground(c);gpu.fill(x,y,n,1," ")end end
local function btn(id,x,y,w,label,c,on)ui[id]={x=x,y=y,w=w,h=2};gpu.setBackground(on and C.white or c);gpu.fill(x,y,w,2," ");txt(x+math.max(1,math.floor((w-#label)/2)),y,fit(label,w-2),on and c or C.white,on and C.white or c)end
local function hit(id,x,y)local b=ui[id];return b and x>=b.x and x<b.x+b.w and y>=b.y and y<b.y+b.h end
local function read()active=sc(gen.isActive)==true;local info=sc(gen.getTankInfo);local t=info;if type(info)=="table" and info[1]then t=info[1]end;if type(t)=="table"then capacity=tonumber(t.capacity)or 0;local f=t.fluid;if type(f)=="table"then amount=tonumber(f.amount)or 0;fluid=tostring(f.name or "--")else amount=0;fluid=tostring(f or "--")end else amount=0;capacity=0;fluid="--"end;if mode=="AUTO" and capacity>0 then local p=amount/capacity*100;if p<=low and enabled then sc(gen.setEnabled,false);enabled=false elseif p>=high and not enabled then sc(gen.setEnabled,true);enabled=true end end end
local function set(v)mode="MANUAL";enabled=v;sc(gen.setEnabled,v);msg=v and "GENERATOR ENABLED" or "GENERATOR DISABLED"end
local function header(t)gpu.setBackground(C.panel);gpu.fill(1,1,W,4," ");txt(3,2,"◈ DIESEL // CONTROL",C.cyan,C.panel);txt(math.max(25,math.floor(W*.34)),2,fit(t,math.max(8,W-28)),C.white,C.panel);led(math.max(5,W-23),2,active,C.green,"RUNNING");gpu.setBackground(C.orange);gpu.fill(1,4,W,1," ")end
local function footer()local y=H-3;local gap=1;local n=5;local bw=math.max(7,math.floor((W-4-(n-1)*gap)/n));local x=2;btn("auto",x,y,bw,"AUTO",C.purple,mode=="AUTO");x=x+bw+gap;btn("on",x,y,bw,"ON",C.green,mode=="MANUAL"and enabled);x=x+bw+gap;btn("off",x,y,bw,"OFF",C.red,mode=="MANUAL"and not enabled);x=x+bw+gap;btn("refresh",x,y,bw,"SCAN",C.yellow);x=x+bw+gap;btn("quit",x,y,bw,"EXIT",C.red);txt(3,H,fit(msg,W-6),C.grey,C.panel)end
local function draw()resize();gpu.setBackground(C.bg);gpu.fill(1,1,W,H," ");header("POWER PLANT STATUS");local p=capacity>0 and amount/capacity*100 or 0;local fc=p<=low and C.red or p<high and C.yellow or C.green;local cy=6;local h=H-10;local two=W>=82;local gap=2;local pw=two and math.floor((W-6-gap)/2)or W-6;box(3,cy,pw,h,"GENERATOR CORE",active and C.green or C.red);led(6,cy+3,active,C.green,active and"GENERATOR ACTIVE"or"GENERATOR STOPPED");led(6,cy+5,mode=="AUTO",C.purple,mode=="AUTO"and"AUTO CONTROL"or"MANUAL CONTROL");txt(6,cy+7,"FUEL",C.grey,C.panel);txt(20,cy+7,string.format("%d / %d mB",amount,capacity),fc,C.panel);bar(6,cy+8,pw-8,p,fc);txt(6,cy+10,"LEVEL",C.grey,C.panel);txt(20,cy+10,string.format("%.1f%%",p),fc,C.panel);txt(6,cy+12,"FLUID",C.grey,C.panel);txt(20,cy+12,fit(fluid,pw-23),C.white,C.panel);if two then local x=3+pw+gap;box(x,cy,pw,h,"AUTOMATION",C.purple);txt(x+4,cy+3,"LOW THRESHOLD",C.grey,C.panel);txt(x+22,cy+3,low.." %",C.red,C.panel);txt(x+4,cy+5,"HIGH THRESHOLD",C.grey,C.panel);txt(x+22,cy+5,high.." %",C.green,C.panel);led(x+4,cy+8,enabled,C.green,enabled and"OUTPUT ENABLED"or"OUTPUT DISABLED");txt(x+4,cy+11,"AUTO RANGE",C.grey,C.panel);bar(x+4,cy+12,pw-8,p,C.orange)end;footer()end
local function click(x,y)if hit("auto",x,y)then mode="AUTO";msg="AUTOMATIC CONTROL ON";read()elseif hit("on",x,y)then set(true)elseif hit("off",x,y)then set(false)elseif hit("refresh",x,y)then msg="STATUS UPDATED";read()elseif hit("quit",x,y)then running=false end end
resize();read();draw();while running do local e,a,x,y=event.pull(1);if e=="touch"then click(x,y);read();draw()elseif e=="key_down"then local c=y;if c==string.byte("q")or c==string.byte("Q")then running=false elseif c==string.byte("a")or c==string.byte("A")then mode="AUTO" elseif c==string.byte("m")or c==string.byte("M")then set(true)elseif c==string.byte("o")or c==string.byte("O")then set(false)end;read();draw()end end
gpu.setBackground(C.bg);gpu.fill(1,1,W,H," ")