-- Network.lua
-- BULDACITY/2 network service for OpenComputers 1.7.10.
-- Uses the real OC modem/network-card API: modem.open/send/broadcast and modem_message.
local component=require("component")
local event=require("event")
local computer=require("computer")
local M={PROTOCOL="BULDACITY/2",PORT=4242,TIMEOUT=12,MAX_WIRELESS_STRENGTH=400,modem=nil,wireless=false,wirelessStrength=0,wirelessAvailable=false,wirelessReady=false,wirelessComponent=nil,relayCount=0,accessPointCount=0,relayWirelessCount=0,relayDetected=false,relayPathType="NONE",lastPacketDistance=0,serverAddress=nil,linked=false,linkSince=0,diagnostics={},lastScan={}}
local function allModems()local r={};for a,k in component.list("modem",true)do local m=component.proxy(a);if m then r[#r+1]=m end end;return r end
local function wireless(m)return type(m.setStrength)=="function" or type(m.getStrength)=="function" end
local function scanModems(openPort)local r={};for _,m in ipairs(allModems())do local w=wireless(m);local s=0;local opened=false;if openPort then opened=pcall(function()m.open(M.PORT)end)end;if w and type(m.setStrength)=="function" then pcall(function()m.setStrength(M.MAX_WIRELESS_STRENGTH)end)end;if w and type(m.getStrength)=="function" then pcall(function()s=tonumber(m.getStrength())or 0 end)end;r[#r+1]={address=m.address,type=m.type or"modem",wireless=w,strength=s,port=M.PORT,open=opened or not openPort}end;return r end
local function configure()local ms=scanModems(true);M.modem=ms[1];M.wireless=false;M.wirelessAvailable=false;M.wirelessReady=false;M.wirelessStrength=0;M.wirelessComponent=nil;for _,d in ipairs(ms)do if d.wireless then M.wireless=true;M.wirelessAvailable=true;if d.strength>M.wirelessStrength then M.wirelessStrength=d.strength;M.wirelessComponent=d.address end end end;M.wirelessReady=M.wirelessStrength>0;return#ms>0,ms end
local function paths()M.relayCount=0;M.accessPointCount=0;M.relayWirelessCount=0;for a in component.list("relay",true)do local r=component.proxy(a);if r then M.relayCount=M.relayCount+1;if type(r.setStrength)=="function"then pcall(function()r.setStrength(M.MAX_WIRELESS_STRENGTH)end);M.relayWirelessCount=M.relayWirelessCount+1 end;if type(r.setRepeater)=="function"then pcall(function()r.setRepeater(true)end)end end end;for a in component.list("access_point",true)do local r=component.proxy(a);if r then M.accessPointCount=M.accessPointCount+1;if type(r.setStrength)=="function"then pcall(function()r.setStrength(M.MAX_WIRELESS_STRENGTH)end);M.relayWirelessCount=M.relayWirelessCount+1 end end end;M.relayDetected=M.relayCount>0 or M.accessPointCount>0;if M.accessPointCount>0 and M.relayCount>0 then M.relayPathType="RELAY+ACCESS_POINT"elseif M.accessPointCount>0 then M.relayPathType="ACCESS_POINT"elseif M.relayCount>0 then M.relayPathType=M.relayWirelessCount>0 and"WIRELESS_RELAY"or"WIRED_RELAY"else M.relayPathType="NONE"end end
local function init(port)M.PORT=port or M.PORT;local ok,ms=configure();paths();if not ok then M.lastScan={stage="NO_MODEM",ok=false,time=computer.uptime()};return false,"NO_MODEM"end;M.lastScan={stage="MODEM_READY",ok=true,time=computer.uptime(),modemCount=#ms,modems=ms};return true,M.wireless and"WIRELESS"or"WIRED"end
function M.init(port)return init(port)end
function M.address()local ok,a=pcall(computer.address);return ok and a or"unknown"end
function M.packet(kind,data)return{protocol=M.PROTOCOL,kind=kind,sender=M.address(),time=computer.uptime(),data=data or{}}end
function M.valid(p)return type(p)=="table"and p.protocol==M.PROTOCOL and type(p.kind)=="string"end
local function call(m,method,...)local ok,a=pcall(function()return m[method](m,...)end);return ok,a end
local function transmit(address,kind,data,bcast)local sent=0;local last=nil;local packet=M.packet(kind,data);for _,m in ipairs(allModems())do call(m,"open",M.PORT);local ok,res;if bcast then ok,res=call(m,"broadcast",M.PORT,packet)else ok,res=call(m,"send",address,M.PORT,packet)end;if ok and res~=false then sent=sent+1 else last=res end end;return sent,last end
function M.send(address,kind,data)if not address then return false,"NO_ADDRESS"end;local ok=init(M.PORT);if not ok then return false,"NO_MODEM"end;local sent,last=transmit(address,kind,data,false);return sent>0,sent>0 and nil or tostring(last)end
function M.broadcast(kind,data)local ok=init(M.PORT);if not ok then return false,"NO_MODEM"end;local sent,last=transmit(nil,kind,data,true);return sent>0,sent>0 and nil or tostring(last)end
function M.setWirelessStrength(n)n=tonumber(n);if not n then return false,"BAD_STRENGTH"end;local found=false;for _,m in ipairs(allModems())do if type(m.setStrength)=="function"then local ok=pcall(function()m.setStrength(math.max(0,n))end);found=found or ok end end;M.getWirelessStrength();return found,M.wirelessStrength end
function M.getWirelessStrength()local best=0;for _,m in ipairs(allModems())do if type(m.getStrength)=="function"then local ok,s=pcall(function()return m.getStrength()end);if ok and tonumber(s)and tonumber(s)>best then best=tonumber(s);M.wirelessComponent=m.address end end end;M.wirelessStrength=best;M.wirelessAvailable=best>0 or M.wireless;M.wirelessReady=best>0;return best end
function M.componentCheck()local ok,ms=configure();paths();return{ok=ok,modemCount=#ms,modems=ms,wirelessAvailable=M.wirelessAvailable,wirelessReady=M.wirelessReady,wirelessComponent=M.wirelessComponent,wirelessStrength=M.wirelessStrength,relayCount=M.relayCount,accessPointCount=M.accessPointCount,relayWirelessCount=M.relayWirelessCount,relayDetected=M.relayDetected,relayPathType=M.relayPathType}end
function M.status()local c=M.componentCheck();c.protocol=M.PROTOCOL;c.port=M.PORT;c.server=M.serverAddress;c.linked=M.linked;c.linkSince=M.linkSince;c.lastPacketDistance=M.lastPacketDistance or 0;c.diagnostics=M.diagnostics;c.lastScan=M.lastScan;return c end
function M.getDiagnostics()local r={};for a,d in pairs(M.diagnostics)do r[a]={};for k,v in pairs(d)do r[a][k]=v end end;return r end
local function clientData()return{name=M.name or"BULDACITY CONTROLLER",role="CLIENT",app=M.name or"BULDACITY CONTROLLER",clientAddress=M.address(),serverAddress=M.serverAddress,linked=M.linked,wireless=M.wireless,wirelessAvailable=M.wirelessAvailable,wirelessReady=M.wirelessReady,wirelessComponent=M.wirelessComponent,wirelessStrength=M.wirelessStrength,relayDetected=M.relayDetected,relayPathType=M.relayPathType,relayCount=M.relayCount,accessPointCount=M.accessPointCount,relayWirelessCount=M.relayWirelessCount,modems=scanModems(false)}end
function M.startClient(name,extra)local ok,mode=init(M.PORT);if not ok then return false,mode end;M.name=name or"BULDACITY CONTROLLER";M.extra=extra or{};M.extra.name=M.name;M.extra.role="CLIENT";M.extra.app=M.name;local function hello()M.extra.clientAddress=M.address();M.extra.serverAddress=M.serverAddress;M.extra.linked=M.linked;M.extra.modems=scanModems(false);M.broadcast("HELLO",M.extra)end;hello();if not M.clientListening then M.clientListening=true;event.listen("modem_message",function(_,receiver,sender,port,distance,p)if port~=M.PORT or not M.valid(p)then return end;M.lastPacketDistance=tonumber(distance)or 0;local d=p.data or{};if p.kind=="SERVER_HELLO"then M.serverAddress=sender;M.send(sender,"HELLO",M.extra)elseif p.kind=="LINK_ACK"then M.serverAddress=sender;M.linked=true;M.linkSince=M.linkSince>0 and M.linkSince or computer.uptime();M.send(sender,"LINK_CONFIRM",clientData())elseif p.kind=="PING"then M.serverAddress=sender;M.send(sender,"PONG",{name=M.name,role="CLIENT",app=M.name,clientAddress=M.address(),serverAddress=M.serverAddress,linked=M.linked,wireless=M.wireless,wirelessAvailable=M.wirelessAvailable,wirelessReady=M.wirelessReady,wirelessStrength=M.wirelessStrength,relayDetected=M.relayDetected,relayPathType=M.relayPathType,modems=scanModems(false),id=d.id})elseif p.kind=="INPUT"and type(d)=="table"then if d.event=="key_down"or d.event=="key_up"then pcall(computer.pushSignal,d.event,sender,d.char or 0,d.code or 0)elseif d.event=="touch"then pcall(computer.pushSignal,"touch",sender,d.x or 1,d.y or 1,d.button or 0)elseif d.event=="scroll"then pcall(computer.pushSignal,"scroll",sender,d.x or 0,d.y or 0,d.button or 0)end elseif p.kind=="SCREEN_REQUEST"and M.sendScreen then M.sendScreen(sender)end end)end;if not M.helloTimer then M.helloTimer=event.timer(3,hello,math.huge)end;if not M.heartbeatTimer then M.heartbeatTimer=event.timer(3,function()init(M.PORT);local d=clientData();d.uptime=computer.uptime();if M.serverAddress then M.send(M.serverAddress,"HEARTBEAT",d)else M.broadcast("HEARTBEAT",d)end end,math.huge)end;return true,mode end
function M.sendScreen(address)if not address or not component.isAvailable("gpu")then return false end;local g=component.gpu;local w,h=g.getResolution();M.send(address,"SCREEN_BEGIN",{width=w,height=h});for y=1,h do local cells={};for x=1,w do local ch,fg,bg=g.get(x,y);cells[x]={ch or" ",fg or 0xFFFFFF,bg or 0}end;M.send(address,"SCREEN_ROW",{y=y,cells=cells})end;M.send(address,"SCREEN_END",{width=w,height=h});return true end
function M.startServer(cb)local ok,mode=init(M.PORT);if not ok then return false,mode end;M.server=true;M.serverCallback=cb;if not M.serverListening then M.serverListening=true;event.listen("modem_message",function(_,receiver,sender,port,distance,p)if port~=M.PORT or not M.valid(p)then return end;M.lastPacketDistance=tonumber(distance)or 0;local d=p.data or{};local now=computer.uptime();local q=M.diagnostics[sender]or{address=sender};M.diagnostics[sender]=q;if p.kind=="HELLO"or p.kind=="HEARTBEAT"then for k,v in pairs(d)do q[k]=v end;q.last=now;q.distance=tonumber(distance)or 0;q.wireless=q.distance>0 or d.wireless==true;q.result=q.linked and"LINKED"or"ONLINE";M.send(sender,"LINK_ACK",{serverAddress=M.address(),protocol=M.PROTOCOL,port=M.PORT,linked=true,serverName="BULDACITY TIER-3"});q.pingSent=computer.uptime();M.lastScan={stage="PING_SENT",ok=true,time=q.pingSent,target=sender};M.send(sender,"PING",{from="BULDACITY SERVER",diagnostic=true,id=tostring(q.pingSent)})elseif p.kind=="LINK_CONFIRM"then for k,v in pairs(d)do q[k]=v end;q.last=now;q.distance=tonumber(distance)or 0;q.linked=true;q.result="LINKED";q.serverAddress=M.address()elseif p.kind=="PONG"then for k,v in pairs(d)do q[k]=v end;q.last=now;q.lastPong=now;q.distance=tonumber(distance)or 0;q.wireless=q.distance>0 or d.wireless==true;q.result="PASS";if q.pingSent then q.latency=(now-q.pingSent)*1000 end;M.lastScan={stage="PONG_PASS",ok=true,time=now,target=sender,distance=q.distance}elseif p.kind=="COMPONENT_DATA"then for k,v in pairs(d)do q[k]=v end;q.last=now;q.distance=tonumber(distance)or 0;q.wireless=q.distance>0 or d.wireless==true;M.lastScan={stage="COMPONENT_DATA",ok=true,time=now,target=sender}end;if M.serverCallback then M.serverCallback(sender,p,distance)end end)end;return true,mode end
return M
