-- Reactor Touch Dashboard
-- OpenComputers / Big Reactors / Extreme Reactors
local component=require("component")
local event=require("event")
local gpu=component.gpu
local W,H=120,36
local C={bg=0x0B0F14,panel=0x151B22,blue=0x3B82F6,cyan=0x22D3EE,green=0x22C55E,yellow=0xFACC15,orange=0xF97316,red=0xEF4444,purple=0xA855F7,white=0xF8FAFC,text=0xCBD5E1,muted=0x64748B,dark=0x111827}
local reactors={};local selected=1;local page="HOME";local running=true;local msg="Bereit"
local function sc(o,m,...)if not o or type(o[m])~="function"then return nil end local ok,a=pcall(o[m],o,...);return ok and a or nil end
local function txt(x,y,s,c,b)gpu.setForeground(c or C.text);gpu.setBackground(b or C.bg);gpu.set(x,y,tostring(s))end
local function box(x,y,w,h,t,c)gpu.setBackground(C.panel);gpu.fill(x,y,w,h," ");gpu.setBackground(c or C.blue);gpu.fill(x,y,1,h," ");txt(x+3,y,"[ "..t.." ]",c or C.cyan,C.panel)end
local function btn(x,y,w,t,c,on)gpu.setBackground(on and C.white or c);gpu.fill(x,y,w,3," ");txt(x+math.max(1,math.floor((w-#t)/2)),y+1,t,on and c or C.white,on and C.white or c)end
local function bar(x,y,w,v,m,c)v=tonumber(v)or 0;m=tonumber(m)or 1;local n=math.max(0,math.min(w,math.floor(w*v/m)));gpu.setBackground(C.dark);gpu.fill(x,y,w,2," ");if n>0 then gpu.setBackground(c);gpu.fill(x,y,n,2," ")end end
local function scan()reactors={};for a,t in component.list()do if t=="br_reactor" then reactors[#reactors+1]=component.proxy(a)end end;if selected>#reactors then selected=1 end;msg="Scan: "..#reactors.." Reactor(s)" end
local function draw()gpu.setResolution(W,H);gpu.setBackground(C.bg);gpu.fill(1,1,W,H," ");gpu.setBackground(C.blue);gpu.fill(1,1,W,4," ");txt(3,2,"REACTOR CONTROL // TOUCH PANEL",C.white,C.blue);txt(3,3,"OpenComputers | Big/Extreme Reactors",C.cyan,C.blue)
if #reactors==0 then box(2,6,116,23,"STATUS",C.red);txt(6,10,"Kein br_reactor gefunden.",C.red);txt(6,12,"Adapter mit dem Reactor verbinden und SCAN druecken.",C.muted)else local r=reactors[selected];local active=sc(r,"getActive");local energy=sc(r,"getEnergyStored")or 0;local maxE=sc(r,"getEnergyCapacity")or 1;local fuel=sc(r,"getFuelAmount")or 0;local maxF=sc(r,"getFuelAmountMax")or 1;local waste=sc(r,"getWasteAmount")or 0;local temp=sc(r,"getFuelTemperature")or sc(r,"getCasingTemperature")or 0;if page=="HOME"then box(2,6,36,23,"REACTOR",C.blue);txt(6,8,"STATUS",C.muted);txt(18,8,active and "ONLINE"or"OFFLINE",active and C.green or C.red);txt(6,11,"ENERGY",C.muted);txt(18,11,energy.." RF",C.cyan);bar(6,12,28,energy,maxE,C.cyan);txt(6,15,"FUEL",C.muted);txt(18,15,fuel.." mb",C.yellow);bar(6,16,28,fuel,maxF,C.yellow);txt(6,19,"WASTE",C.muted);txt(18,19,waste.." mb",C.purple);txt(6,22,"TEMP",C.muted);txt(18,22,string.format("%.1f C",temp),temp>1000 and C.red or C.orange)
box(40,6,78,23,"REACTOR OUTPUT",C.orange);txt(44,8,"ENERGY BUFFER",C.muted);txt(65,8,string.format("%.1f%%",energy/maxE*100),C.green);bar(44,10,68,energy,maxE,C.green);txt(44,13,"FUEL BUFFER",C.muted);txt(65,13,string.format("%.1f%%",fuel/maxF*100),C.yellow);bar(44,15,68,fuel,maxF,C.yellow);txt(44,18,"TEMPERATURE",C.muted);txt(65,18,string.format("%.1f C",temp),temp>1000 and C.red or C.orange);bar(44,20,68,temp,2000,temp>1000 and C.red or C.orange);txt(44,23,"SELECTED",C.muted);txt(65,23,"#"..selected.." / "..#reactors,C.cyan)
else box(2,6,116,23,"DETAILS",C.cyan);txt(7,9,"ACTIVE",C.muted);txt(25,9,active and "YES"or"NO",active and C.green or C.red);txt(7,12,"ENERGY",C.muted);txt(25,12,energy.." / "..maxE.." RF",C.cyan);txt(7,15,"FUEL",C.muted);txt(25,15,fuel.." / "..maxF.." mb",C.yellow);txt(7,18,"WASTE",C.muted);txt(25,18,waste.." mb",C.purple);txt(7,21,"TEMPERATURE",C.muted);txt(25,21,string.format("%.1f C",temp),C.orange)end end
box(2,31,116,4,"TOUCH CONTROLS",C.blue);btn(5,31,18,"HOME",C.blue,page=="HOME");btn(26,31,18,"DETAILS",C.cyan,page=="DETAILS");btn(47,31,18,"PREV",C.purple,false);btn(68,31,18,"NEXT",C.green,false);btn(89,31,12,"SCAN",C.yellow,false);btn(104,31,12,"QUIT",C.red,false);txt(5,35,msg,C.muted)end
local function click(x,y)if y>=31 and y<=33 then if x>=5 and x<23 then page="HOME"elseif x>=26 and x<44 then page="DETAILS"elseif x>=47 and x<65 then selected=math.max(1,selected-1)elseif x>=68 and x<86 then selected=math.min(#reactors,selected+1)elseif x>=89 and x<101 then scan()elseif x>=104 and x<116 then running=false end end end
scan();draw();while running do local e,a,x,y=event.pull(1);if e=="touch"then click(x,y);draw()elseif e=="key_down"then local c=y;if c==string.byte("q")or c==string.byte("Q")then running=false elseif c==string.byte("r")or c==string.byte("R")then scan()elseif c==string.byte("1")then page="HOME"elseif c==string.byte("2")then page="DETAILS"elseif c==200 then selected=math.max(1,selected-1)elseif c==208 then selected=math.min(#reactors,selected+1)end;draw()end end
