-- RotaryCraft Touch Dashboard
-- Minecraft 1.7.10 / RotaryCraft V33a / OpenComputers 1.8.10
local component=require("component")
local event=require("event")
local computer=require("computer")
local gpu=component.gpu
local W,H=120,40; local running=true; local page="HOME"; local selected=1; local comps={}; local auto=true; local msg="Bereit"
local C={bg=0x071019,panel=0x0E1A25,header=0x123B59,line=0x24445A,white=0xF2F7FB,muted=0x8FA7B8,blue=0x4CB8FF,cyan=0x59E6FF,green=0x55E58A,yellow=0xFFD45C,orange=0xFF9B55,red=0xFF5F6D,purple=0xC28CFF}
local function sc(o,m,...) if not o or type(o[m])~="function" then return nil end local ok,a,b=pcall(o[m],o,...); return ok and a or nil,b end
local function txt(x,y,s,c,b) gpu.setForeground(c or C.white); gpu.setBackground(b or C.bg); gpu.set(x,y,tostring(s)) end
local function box(x,y,w,h,t,c) gpu.setBackground(C.panel); gpu.fill(x,y,w,h," "); gpu.setBackground(c or C.blue); gpu.fill(x,y,1,h," "); txt(x+3,y,"[ "..t.." ]",c or C.cyan,C.panel) end
local function btn(x,y,w,t,c,on) gpu.setBackground(on and C.white or c); gpu.fill(x,y,w,3," "); txt(x+math.max(1,math.floor((w-#t)/2)),y+1,t,on and c or C.white,on and C.white or c) end
local function bar(x,y,w,v,m,c) v=tonumber(v) or 0;m=tonumber(m) or 1;local n=math.max(0,math.min(w,math.floor(w*v/m)));gpu.setBackground(0x17232D);gpu.fill(x,y,w,2," ");if n>0 then gpu.setBackground(c);gpu.fill(x,y,n,2," ") end end
local function discover() comps={};for a,t in component.list() do local p=component.proxy(a);local score=0;for _,m in ipairs({"getOmega","getTorque","getPower","getTemperature","getECU","getFuelAmount"}) do if type(p[m])=="function" then score=score+1 end end;comps[#comps+1]={address=a,type=t,p=p,score=score} end;table.sort(comps,function(a,b)return a.score>b.score end);if selected>#comps then selected=1 end end
local function val(p,ms) for _,m in ipairs(ms) do local v=sc(p,m);if tonumber(v) then return tonumber(v),m end end end
local function data() local c=comps[selected];if not c then return {} end;local p=c.p;local o,om=val(p,{"getOmega","getSpeed","getRPM","getRpm"});local t,tm=val(p,{"getTorque"});local pw,pm=val(p,{"getPower"});local temp=val(p,{"getTemperature","getTemp"});local ecu=val(p,{"getECU","getECUPower"});if not pw and o and t then pw=o*t end;local active=sc(p,"isActive");if active==nil then active=sc(p,"isRunning") end;return {o=o,t=t,pw=pw,temp=temp,ecu=ecu,active=active,om=om,tm=tm} end
local function draw() gpu.setResolution(W,H);gpu.setBackground(C.bg);gpu.fill(1,1,W,H," ");gpu.setBackground(C.header);gpu.fill(1,1,W,4," ");txt(3,2,"ROTARYCRAFT // INDUSTRIAL CONTROL",C.white,C.header);txt(3,3,"TOUCH DASHBOARD   MC 1.7.10 | V33a | OC 1.8.10",C.cyan,C.header);txt(95,2,auto and "LIVE" or "PAUSE",auto and C.green or C.yellow,C.header)
 if page=="HOME" then local d=data();box(2,6,36,12,"DEVICE",C.blue);local c=comps[selected];txt(5,8,"TYPE",C.muted);txt(16,8,c and c.type or "NONE",C.white);txt(5,10,"ADDRESS",C.muted);txt(16,10,c and c.address:sub(1,20) or "-",C.blue);txt(5,12,"SCORE",C.muted);txt(16,12,c and c.score or 0,C.green);txt(5,15,"STATUS",C.muted);txt(16,15,d.active==true and "ACTIVE" or d.active==false and "STOP" or "UNKNOWN",d.active==true and C.green or d.active==false and C.red or C.yellow)
  box(40,6,24,6,"DREHZAHL",C.cyan);txt(43,8,d.o and string.format("%.2f",d.o) or "N/A",C.cyan);bar(43,10,18,d.o,math.max(d.o or 1,1)*1.25,C.cyan)
  box(66,6,24,6,"DREHMOMENT",C.orange);txt(69,8,d.t and string.format("%.2f",d.t) or "N/A",C.orange);bar(69,10,18,d.t,math.max(d.t or 1,1)*1.25,C.orange)
  box(92,6,26,6,"LEISTUNG",C.green);txt(95,8,d.pw and string.format("%.1f",d.pw) or "N/A",C.green);bar(95,10,20,d.pw,math.max(d.pw or 1,1)*1.25,C.green)
  box(40,14,78,8,"MACHINE",C.purple);txt(44,16,"TEMPERATUR",C.muted);txt(60,16,d.temp and string.format("%.1f C",d.temp) or "N/A",C.yellow);txt(78,16,"ECU",C.muted);txt(88,16,d.ecu and string.format("%.1f",d.ecu) or "N/A",C.purple);txt(44,19,"POWER",C.muted);txt(60,19,d.pw and string.format("%.1f",d.pw) or "N/A",C.green);txt(78,19,"ROTARY API",C.muted);txt(92,19,(d.om or "-").." / "..(d.tm or "-"),C.cyan)
 else box(2,6,116,27,page=="COMP" and "COMPONENT SCANNER" or "METHODS",C.cyan);if page=="COMP" then for i,c in ipairs(comps) do if i<=22 then local y=8+i;txt(5,y,i,C.cyan);txt(10,y,c.type,C.white);txt(34,y,c.score>0 and "ROTARY" or "OTHER",c.score>0 and C.green or C.muted);txt(50,y,c.address:sub(1,34),C.blue);end end;else local c=comps[selected];if c then local y=9;for m in pairs(c.p) do if type(c.p[m])=="function" then txt(6,y,"* "..m,C.green);y=y+1;if y>31 then break end end end else txt(6,10,"Keine Komponente",C.red) end end end
 box(2,35,116,4,"TOUCH MENU",C.blue);btn(5,35,20,"HOME",C.blue,page=="HOME");btn(28,35,20,"COMP",C.cyan,page=="COMP");btn(51,35,20,"METHODS",C.purple,page=="METHODS");btn(74,35,18,"SCAN",C.yellow,false);btn(95,35,18,"AUTO",C.green,auto);btn(116,35,2,"",C.red,false);txt(5,39,msg,C.muted)
end
local function click(x,y) if y>=35 then if x>=5 and x<25 then page="HOME" elseif x>=28 and x<48 then page="COMP" elseif x>=51 and x<71 then page="METHODS" elseif x>=74 and x<92 then discover();msg="Scan abgeschlossen" elseif x>=95 and x<113 then auto=not auto;msg=auto and "Live aktiviert" or "Live pausiert" end end end
discover();draw();while running do local e,a,x,y=event.pull(1);if e=="touch" then click(x,y);draw() elseif e=="key_down" then local c=y;if c==string.byte("q") or c==string.byte("Q") then running=false elseif c==string.byte("r") or c==string.byte("R") then discover() elseif c==string.byte("a") or c==string.byte("A") then auto=not auto elseif c==string.byte("1") then page="HOME" elseif c==string.byte("2") then page="COMP" elseif c==string.byte("3") then page="METHODS" end;draw() end end
