-- RotaryCraftDashboard_Modern.lua
-- Modern responsive LED dashboard for RotaryCraft V33a / OC 1.8.10 / MC 1.7.10
local component=require("component")
local event=require("event")
local gpu=component.gpu
local computer=require("computer")
local W,H=80,25;local running=true;local page="HOME";local selected=1;local comps={};local live=true;local msg="SYSTEM READY";local ui={}
local C={bg=0x05080D,panel=0x0D141D,panel2=0x111D29,line=0x26384A,blue=0x35B9FF,cyan=0x55F5FF,green=0x39FF88,red=0xFF4F68,yellow=0xFFE36E,orange=0xFF9F43,purple=0xB47CFF,white=0xF4FAFF,grey=0x7F95A8,off=0x24313C}
local function resize()local mw,mh=gpu.maxResolution();local cw,ch=gpu.getResolution();W,H=mw or cw,mh or ch;if W<40 then W=40 end;if H<16 then H=16 end;pcall(gpu.setResolution,W,H);W,H=gpu.getResolution()end
local function sc(o,m,...)if not o or type(o[m])~="function"then return nil end;local ok,a,b=pcall(o[m],o,...);return ok and a or nil,b end
local function txt(x,y,s,c,b)gpu.setForeground(c or C.white);gpu.setBackground(b or C.bg);gpu.set(x,y,tostring(s))end
local function fit(s,n)s=tostring(s or "");return #s<=n and s or s:sub(1,math.max(1,n-1)).."…"end
local function box(x,y,w,h,t,c)gpu.setBackground(C.panel);gpu.fill(x,y,w,h," ");gpu.setBackground(C.line);gpu.fill(x,y,w,1," ");txt(x+2,y,"◆ "..fit(t,w-5),c or C.cyan,C.panel)end
local function led(x,y,on,c,label)local cc=on and c or C.off;gpu.setBackground(cc);gpu.fill(x,y,2,1," ");txt(x+3,y,fit(label or "STATUS",18),on and cc or C.grey,C.panel)end
local function bar(x,y,w,v,m,c)v=tonumber(v)or 0;m=math.max(tonumber(m)or 1,1);local n=math.floor(math.max(0,math.min(m,v))/m*w);gpu.setBackground(C.panel2);gpu.fill(x,y,w,1," ");if n>0 then gpu.setBackground(c);gpu.fill(x,y,n,1," ")end end
local function btn(id,x,y,w,label,c,on)ui[id]={x=x,y=y,w=w,h=2};gpu.setBackground(on and C.white or c);gpu.fill(x,y,w,2," ");txt(x+math.max(1,math.floor((w-#label)/2)),y,fit(label,w-2),on and c or C.white,on and C.white or c)end
local function hit(id,x,y)local b=ui[id];return b and x>=b.x and x<b.x+b.w and y>=b.y and y<b.y+b.h end
local function discover()comps={};for a,t in component.list()do local p=component.proxy(a);local score=0;for _,m in ipairs({"getOmega","getTorque","getPower","getTemperature","getECU","getFuelAmount"})do if type(p[m])=="function"then score=score+1 end end;comps[#comps+1]={address=a,type=t,p=p,score=score}end;table.sort(comps,function(a,b)return a.score>b.score end);if selected>#comps then selected=1 end;msg="DEVICE SCAN COMPLETE"end
local function val(p,ms)for _,m in ipairs(ms)do local v=sc(p,m);if tonumber(v)then return tonumber(v),m end end end
local function data()local c=comps[selected];if not c then return{}end;local p=c.p;local o,om=val(p,{"getOmega","getSpeed","getRPM","getRpm"});local t,tm=val(p,{"getTorque"});local pw=val(p,{"getPower"});local temp=val(p,{"getTemperature","getTemp"});local ecu=val(p,{"getECU","getECUPower"});if not pw and o and t then pw=o*t end;local ac=sc(p,"isActive");if ac==nil then ac=sc(p,"isRunning")end;return{o=o,t=t,pw=pw,temp=temp,ecu=ecu,active=ac,om=om,tm=tm}end
local function header(t)gpu.setBackground(C.panel);gpu.fill(1,1,W,4," ");txt(3,2,"◈ ROTARY // CONTROL",C.cyan,C.panel);txt(math.max(25,math.floor(W*.34)),2,fit(t,math.max(8,W-28)),C.white,C.panel);led(math.max(5,W-22),2,live,C.green,live and"LIVE"or"PAUSE");gpu.setBackground(C.orange);gpu.fill(1,4,W,1," ")end
local function footer()local y=H-3;local gap=1;local n=5;local bw=math.max(7,math.floor((W-4-(n-1)*gap)/n));local x=2;btn("home",x,y,bw,"HOME",C.purple,page=="HOME");x=x+bw+gap;btn("scan",x,y,bw,"SCAN",C.yellow);x=x+bw+gap;btn("next",x,y,bw,"NEXT",C.blue);x=x+bw+gap;btn("live",x,y,bw,"LIVE",C.green,live);x=x+bw+gap;btn("quit",x,y,bw,"EXIT",C.red);txt(3,H,fit(msg,W-6),C.grey,C.panel)end
local function drawHome()header("INDUSTRIAL TELEMETRY");local d=data();local cy=6;local h=H-10;local two=W>=82;local gap=2;local pw=two and math.floor((W-6-gap)/2)or W-6;box(3,cy,pw,h,"MACHINE",C.blue);local c=comps[selected];led(6,cy+3,c~=nil and d.active==true,C.green,d.active==true and"MACHINE ACTIVE"or"MACHINE STOPPED");txt(6,cy+5,"TYPE",C.grey,C.panel);txt(18,cy+5,c and fit(c.type,pw-20)or"NONE",C.white,C.panel);txt(6,cy+7,"SPEED",C.grey,C.panel);txt(18,cy+7,d.o and string.format("%.2f",d.o)or"N/A",C.cyan,C.panel);bar(6,cy+8,pw-8,d.o,math.max(d.o or 1,1)*1.25,C.cyan);txt(6,cy+10,"TORQUE",C.grey,C.panel);txt(18,cy+10,d.t and string.format("%.2f",d.t)or"N/A",C.orange,C.panel);txt(6,cy+12,"POWER",C.grey,C.panel);txt(18,cy+12,d.pw and string.format("%.1f",d.pw)or"N/A",C.green,C.panel);txt(6,cy+14,"TEMP",C.grey,C.panel);txt(18,cy+14,d.temp and string.format("%.1f C",d.temp)or"N/A",C.yellow,C.panel);if two then local x=3+pw+gap;box(x,cy,pw,h,"SYSTEM STATUS",C.purple);txt(x+4,cy+3,"SELECTED UNIT",C.grey,C.panel);txt(x+22,cy+3,selected.." / "..#comps,C.cyan,C.panel);txt(x+4,cy+5,"ECU",C.grey,C.panel);txt(x+22,cy+5,d.ecu and string.format("%.1f",d.ecu)or"N/A",C.purple,C.panel);led(x+4,cy+8,live,C.green,"LIVE TELEMETRY");led(x+4,cy+10,c~=nil,C.blue,"DEVICE LINK");txt(x+4,cy+13,"API",C.grey,C.panel);txt(x+22,cy+13,fit((d.om or"-").." / "..(d.tm or"-"),pw-23),C.cyan,C.panel)end;footer()end
local function drawScan()header("DEVICE MATRIX");local y=6;local h=H-10;local w=W-6;box(3,y,w,h,"CONNECTED COMPONENTS",C.cyan);local rows=math.max(1,h-4);for i=1,math.min(rows,#comps)do local c=comps[i];local yy=y+2+i;txt(6,yy,string.format("%02d",i),C.cyan,C.panel);txt(11,yy,fit(c.type,18),C.white,C.panel);txt(31,yy,c.score>0 and"ROTARY"or"OTHER",c.score>0 and C.green or C.grey,C.panel);txt(W-22,yy,fit(c.address,18),C.blue,C.panel)end;if #comps==0 then txt(7,y+4,"NO COMPONENTS",C.red,C.panel)end;footer()end
local function draw()resize();gpu.setBackground(C.bg);gpu.fill(1,1,W,H," ");if page=="HOME"then drawHome()else drawScan()end end
local function click(x,y)if hit("home",x,y)then page="HOME"elseif hit("scan",x,y)then discover()elseif hit("next",x,y)then if #comps>0 then selected=selected%#comps+1 end elseif hit("live",x,y)then live=not live;msg=live and"LIVE TELEMETRY ON"or"LIVE TELEMETRY PAUSED"elseif hit("quit",x,y)then running=false end end
resize();discover();draw();while running do local e,a,x,y=event.pull(1);if e=="touch"then click(x,y);draw()elseif e=="key_down"then local c=y;if c==string.byte("q")or c==string.byte("Q")then running=false elseif c==string.byte("r")or c==string.byte("R")then discover()elseif c==string.byte("a")or c==string.byte("A")then live=not live elseif c==string.byte("n")or c==string.byte("N")then if #comps>0 then selected=selected%#comps+1 end end;draw()end end
gpu.setBackground(C.bg);gpu.fill(1,1,W,H," ")