-- RotaryCraftDashboard_Modern.lua
-- Adaptive NEON HUD / RotaryCraft V33a / OpenComputers 1.8.10 / MC 1.7.10
local component=require("component") local event=require("event") local computer=require("computer") local gpu=component.gpu
local W,H=80,25 local page="HOME" local selected=1 local comps={} local live=true local run=true local msg="SYSTEM READY" local pulse=0 local ui={}
local C={bg=0x03060B,panel=0x0A111B,panel2=0x101C29,line=0x214057,cyan=0x35E8FF,blue=0x438CFF,green=0x35FF9A,red=0xFF466D,yellow=0xFFE36A,purple=0xC56BFF,pink=0xFF4CCB,orange=0xFF9D45,white=0xF3FAFF,grey=0x7D96AA,off=0x263541}
local function safe(f,...)local ok,a,b=pcall(f,...);if ok then return a,b end end
local function resize()local mw,mh=safe(gpu.maxResolution);local cw,ch=safe(gpu.getResolution);mw=mw or cw or 80;mh=mh or ch or 25;safe(gpu.setResolution,mw,mh);W,H=safe(gpu.getResolution);W=W or mw;H=H or mh end
local function call(o,m,...)if not o or type(o[m])~="function"then return nil end;local ok,a=pcall(o[m],o,...);if ok then return a end;ok,a=pcall(o[m],...);if ok then return a end end
local function txt(x,y,s,fg,bg)if x<1 or y<1 or x>W or y>H then return end;gpu.setForeground(fg or C.white);gpu.setBackground(bg or C.bg);gpu.set(x,y,tostring(s))end
local function fit(s,n)s=tostring(s or "");n=math.max(1,n or 1);return #s<=n and s or n==1 and s:sub(1,1) or s:sub(1,n-1).."…" end
local function panel(x,y,w,h,t,c)gpu.setBackground(C.panel);gpu.fill(x,y,w,h," ");gpu.setBackground(c);gpu.fill(x,y,w,1," ");txt(x+2,y,"◆ "..fit(t,w-5),C.white,c)end
local function led(x,y,on,c,t)local cc=on and c or C.off;gpu.setBackground(cc);gpu.fill(x,y,2,1," ");txt(x+3,y,fit(t or "OFFLINE",W-x-3),on and cc or C.grey,C.panel)end
local function bar(x,y,w,p,c)p=math.max(0,math.min(100,tonumber(p)or 0));gpu.setBackground(C.panel2);gpu.fill(x,y,w,1," ");local n=math.floor(w*p/100);if n>0 then gpu.setBackground(c);gpu.fill(x,y,n,1," ")end end
local function btn(id,x,y,w,t,c,on)ui[id]={x=x,y=y,w=w,h=2};gpu.setBackground(on and C.white or c);gpu.fill(x,y,w,2," ");txt(x+math.max(1,math.floor((w-#t)/2)),y,fit(t,w-2),on and c or C.white,on and C.white or c)end
local function hit(id,x,y)local b=ui[id];return b and x>=b.x and x<b.x+b.w and y>=b.y and y<b.y+b.h end
local function discover()comps={};for a,t in component.list()do local p=component.proxy(a);local score=0;for _,m in ipairs({"getOmega","getTorque","getPower","getTemperature","getECU","getFuelAmount"})do if type(p[m])=="function"then score=score+1 end end;if score>0 then comps[#comps+1]={address=a,type=t,p=p,score=score}end end;table.sort(comps,function(a,b)return a.score>b.score end);if selected>#comps then selected=1 end;msg="DEVICE SCAN COMPLETE"end
local function val(p,ms)for _,m in ipairs(ms)do local v=call(p,m);if tonumber(v)then return tonumber(v),m end end end
local function data()local c=comps[selected];if not c then return{}end;local p=c.p;local o,om=val(p,{"getOmega","getSpeed","getRPM","getRpm"});local t,tm=val(p,{"getTorque"});local pw=val(p,{"getPower"});local temp=val(p,{"getTemperature","getTemp"});local ecu=val(p,{"getECU","getECUPower"});if not pw and o and t then pw=o*t end;local ac=call(p,"isActive");if ac==nil then ac=call(p,"isRunning")end;return{o=o,t=t,pw=pw,temp=temp,ecu=ecu,active=ac,om=om,tm=tm}end
local function header(t)local blink=pulse%2==0;gpu.setBackground(C.panel);gpu.fill(1,1,W,4," ");txt(2,1,"╔ ROTARY // NEON CORE ╗",C.cyan,C.panel);txt(3,2,fit(t,W-32),C.white,C.panel);led(math.max(5,W-25),2,live,blink and C.green or C.cyan,"LIVE");gpu.setBackground(C.orange);gpu.fill(1,4,W,1," ")end
local function footer()local y=H-3;local n=6;local gap=1;local bw=math.max(3,math.floor((W-4-(n-1)*gap)/n));local x=2;btn("home",x,y,bw,"HOME",C.purple,page=="HOME");x=x+bw+gap;btn("scan",x,y,bw,"SCAN",C.yellow);x=x+bw+gap;btn("next",x,y,bw,"NEXT",C.blue);x=x+bw+gap;btn("live",x,y,bw,"LIVE",C.green,live);x=x+bw+gap;btn("pc",x,y,bw,"PC",C.cyan,page=="PC");x=x+bw+gap;btn("exit",x,y,bw,"EXIT",C.red);txt(2,H,fit(msg,W-4),C.grey,C.bg)end
local function drawHome()header("INDUSTRIAL TELEMETRY");local d=data();local y=6;local h=H-10;local two=W>=76;local gap=2;local pw=two and math.floor((W-6-gap)/2)or W-6;panel(3,y,pw,h,"MACHINE CORE",C.blue);local c=comps[selected];led(6,y+3,c and d.active==true,C.green,d.active==true and"MACHINE ACTIVE"or"MACHINE STOPPED");txt(6,y+5,"TYPE",C.grey,C.panel);txt(18,y+5,c and fit(c.type,pw-20)or"NONE",C.white,C.panel);txt(6,y+7,"SPEED",C.grey,C.panel);txt(18,y+7,d.o and string.format("%.2f",d.o)or"N/A",C.cyan,C.panel);txt(6,y+9,"TORQUE",C.grey,C.panel);txt(18,y+9,d.t and string.format("%.2f",d.t)or"N/A",C.orange,C.panel);txt(6,y+11,"POWER",C.grey,C.panel);txt(18,y+11,d.pw and string.format("%.1f",d.pw)or"N/A",C.green,C.panel);txt(6,y+13,"TEMP",C.grey,C.panel);txt(18,y+13,d.temp and string.format("%.1f C",d.temp)or"N/A",C.yellow,C.panel);if d.o then bar(6,y+15,pw-8,math.min(100,d.o/(math.max(d.o,1)*1.25)*100),C.cyan)end;if two then local x=3+pw+gap;panel(x,y,pw,h,"SYSTEM MATRIX",C.purple);txt(x+4,y+3,"UNIT",C.grey,C.panel);txt(x+20,y+3,selected.." / "..#comps,C.cyan,C.panel);txt(x+4,y+5,"ECU",C.grey,C.panel);txt(x+20,y+5,d.ecu and string.format("%.1f",d.ecu)or"N/A",C.purple,C.panel);led(x+4,y+8,live,C.green,"LIVE TELEMETRY");led(x+4,y+10,c~=nil,C.blue,"DEVICE LINK");txt(x+4,y+13,"API",C.grey,C.panel);txt(x+20,y+13,fit((d.om or"-").." / "..(d.tm or"-"),pw-22),C.cyan,C.panel);txt(x+4,y+15,"HUD",C.grey,C.panel);txt(x+20,y+15,(W>=150 and"ULTRA 160x50"or W>=75 and"WIDE"or"COMPACT"),C.orange,C.panel)end;footer()end
local function drawPC()header("OPENCOMPUTERS // PC MONITOR");local y=6;local h=H-10;local w=W-6;panel(3,y,w,h,"COMPUTER CORE",C.cyan);local e,me=safe(computer.energy),safe(computer.maxEnergy);local t,f=safe(computer.totalMemory),safe(computer.freeMemory);txt(6,y+3,"UPTIME",C.grey,C.panel);txt(24,y+3,string.format("%.1fs",computer.uptime()),C.cyan,C.panel);txt(6,y+5,"CLOCK",C.grey,C.panel);txt(24,y+5,os.date("%H:%M:%S"),C.white,C.panel);if e and me then txt(6,y+7,"ENERGY",C.grey,C.panel);txt(24,y+7,string.format("%.0f / %.0f",e,me),C.yellow,C.panel);bar(24,y+8,math.max(8,w-30),e/me*100,C.yellow)end;if t and f then txt(6,y+10,"MEMORY",C.grey,C.panel);txt(24,y+10,string.format("%d / %d B",t-f,t),C.purple,C.panel);bar(24,y+11,math.max(8,w-30),(t-f)/t*100,C.purple)end;local rw,rh=safe(gpu.getResolution);local dep=safe(gpu.getDepth);txt(6,y+13,"GPU",C.grey,C.panel);txt(24,y+13,string.format("%dx%d / %s bit",rw or W,rh or H,tostring(dep or"?")),C.cyan,C.panel);txt(6,y+15,"DEVICES",C.grey,C.panel);txt(24,y+15,#comps,C.green,C.panel);footer()end
local function drawScan()header("DEVICE MATRIX");local y=6;local h=H-10;local w=W-6;panel(3,y,w,h,"ROTARY COMPONENTS",C.cyan);local rows=math.max(1,h-3);for i=1,math.min(rows,#comps)do local c=comps[i];local yy=y+1+i;txt(6,yy,string.format("%02d",i),C.cyan,C.panel);txt(11,yy,fit(c.type,18),C.white,C.panel);txt(31,yy,"ROTARY",C.green,C.panel)end;if #comps==0 then txt(7,y+4,"NO ROTARY COMPONENT",C.red,C.panel)end;footer()end
local function draw()resize();gpu.setBackground(C.bg);gpu.fill(1,1,W,H," ");if page=="HOME"then drawHome()elseif page=="PC"then drawPC()else drawScan()end end
resize();discover();draw();while run do local e,a,x,y=event.pull(1);if e=="touch"then if hit("home",x,y)then page="HOME"elseif hit("scan",x,y)then discover()elseif hit("next",x,y)then if #comps>0 then selected=selected%#comps+1 end elseif hit("live",x,y)then live=not live;msg=live and"LIVE TELEMETRY ON"or"TELEMETRY PAUSED"elseif hit("pc",x,y)then page="PC"elseif hit("exit",x,y)then run=false end;draw()elseif e=="key_down"then local c=y;if c==string.byte("q")or c==string.byte("Q")then run=false elseif c==string.byte("r")or c==string.byte("R")then discover()elseif c==string.byte("n")or c==string.byte("N")then if #comps>0 then selected=selected%#comps+1 end elseif c==string.byte("p")or c==string.byte("P")then page="PC"end;draw()end;pulse=pulse+1 end
gpu.setBackground(C.bg);gpu.fill(1,1,W,H," ")