-- BULDACITY SGCraft CONTROLLER v3
-- Realistic control-room UI using SGCraftAPI + SGCraftVisual.
local component=require("component");local event=require("event");local computer=require("computer");local serialization=require("serialization");local gpu=component.gpu
local API=dofile("/home/SGCraftAPI.lua");local V=dofile("/home/SGCraftVisual.lua");local C=V.C;local W,H=gpu.getResolution()
local page="HOME";local gates={};local sel=1;local target="";local book={};local logs={};local buttons={};local notice="BOOT";local t=0;local last=0;local cfg="/home/sgcraft-addressbook.cfg"
local function tx(x,y,s,c,b) V.text(x,y,s,c,b or C.metal) end
local function panel(x,y,w,h,title,c) V.fill(x,y,w,h,C.metal);V.line(x,y,w,c);tx(x+2,y,"[ "..V.fit(title,w-5).." ]",C.white,c) end
local function btn(id,x,y,w,h,s,c,on) buttons[id]={x=x,y=y,w=w,h=h};V.fill(x,y,w,h,on and C.white or c);tx(x+math.max(1,math.floor((w-#s)/2)),y+math.floor(h/2),s,on and c or C.white,on and C.white or c) end
local function hit(x,y) for id,b in pairs(buttons) do if x>=b.x and x<b.x+b.w and y>=b.y and y<b.y+b.h then return id end end end
local function log(s) logs[#logs+1]=os.date("%H:%M:%S").."  "..s;while #logs>12 do table.remove(logs,1) end;notice=s end
local function cur() return gates[sel] end
local function read() return API.read(cur()) end
local function scan() local old=cur() and cur().address;gates=API.list();sel=1;if old then for i,g in ipairs(gates) do if g.address==old then sel=i end end end;last=computer.uptime();log(#gates>0 and ("BUS / "..#gates.." STARGATE INTERFACE(S)") or "BUS / NO STARGATE INTERFACE") end
local function save() local f=io.open(cfg,"w");if f then f:write(serialization.serialize(book));f:close() end end
local function load() local f=io.open(cfg,"r");if f then local s=f:read("*a");f:close();local ok,x=pcall(serialization.unserialize,s);if ok and type(x)=="table" then book=x end end end
local function norm(a) return tostring(a or ""):gsub("[^%w]",""):upper() end
local function dial(a) a=norm(a);target=a;if #a~=7 and #a~=9 then log("DIAL / ADDRESS MUST HAVE 7 OR 9 SYMBOLS");return end;local g=cur();local d=API.read(g);if not g or d.state=="Offline" or d.localAddress=="" then log("DIAL / GATE NOT READY");return end;local ok,n=API.energyToDial(g,a);if ok and tonumber(n) and tonumber(n)>d.energy then log("DIAL / INSUFFICIENT ENERGY");return end;local yes,x,e=API.dial(g,a);log(yes and ("DIAL / STARTED / "..a) or ("DIAL / ERROR / "..tostring(e or x))) end
local function iris() local g=cur();if not g then return end;local d=API.read(g);local open=d.iris=="Closed";local ok,x,e;if open then ok,x,e=API.openIris(g) else ok,x,e=API.closeIris(g) end;log(ok and (open and "IRIS / OPEN" or "IRIS / CLOSE") or "IRIS / ERROR / "..tostring(e or x)) end
local function disconnect() local g=cur();if not g then return end;local ok,x,e=API.disconnect(g);log(ok and "GATE / DISCONNECT" or "GATE / ERROR / "..tostring(e or x)) end
local function header(d) V.fill(1,1,W,5,C.black);tx(2,1,"BULDACITY // SGCraft COMMAND",C.cyan,C.black);tx(2,2,"REAL-TIME STARGATE CONTROL / MC 1.7.10",C.muted,C.black);local s=d and d.state or "NO INTERFACE";local col=s=="Connected" and C.green or (s=="Idle" and C.yellow or (s=="NO INTERFACE" and C.red or C.cyan));tx(W-20,1,V.fit(s,18),col,C.black);tx(2,4,V.fit(notice,W-4),C.muted,C.black);V.line(1,5,W,C.cyan) end
local function telemetry(x,y,w,h,d) panel(x,y,w,h,"LIVE TELEMETRY",C.yellow);local function r(n,l,v,c) tx(x+2,y+n,l,C.muted);tx(x+14,y+n,V.fit(v,w-16),c or C.white) end;r(2,"STATE",d.state,d.state=="Connected" and C.green or C.yellow);r(4,"DIRECTION",d.direction=="" and "-" or d.direction);r(6,"CHEVRONS",tostring(d.engaged).." / 9",C.orange);r(8,"IRIS",d.iris,d.iris=="Closed" and C.green or C.yellow);r(10,"LOCAL",d.localAddress=="" and "-" or d.localAddress);r(12,"REMOTE",d.remoteAddress=="" and "-" or d.remoteAddress,C.cyan);V.bar(x+2,y+14,w-4,"ENERGY",d.energy,1000,C.cyan,C.metal);r(16,"API",d.ok and "HEALTHY" or "ERROR",d.ok and C.green or C.red) end
local function bus(x,y,w,h) panel(x,y,w,h,"INTERFACE BUS",C.blue);if #gates==0 then tx(x+2,y+3,"NO STARGATE COMPONENT",C.red);tx(x+2,y+5,"Check interface placement and cable.",C.muted) else for i,g in ipairs(gates) do local yy=y+2+(i-1)*4;if yy>y+h-4 then break end;local d=API.read(g);local on=i==sel;V.fill(x+1,yy,w-2,3,on and C.metal2 or C.metal);tx(x+3,yy,(on and "> " or "  ")..V.fit(g.address,w-6),C.white);tx(x+5,yy+1,d.state,d.state=="Connected" and C.green or C.yellow);buttons["g"..i]={x=x+1,y=yy,w=w-2,h=3} end end;btn("scan",x+2,y+h-3,w-4,2,"RESCAN BUS",C.blue) end
local function controls(y) panel(2,y,W-3,5,"COMMAND DECK",C.green);btn("home",4,y+2,9,2,"HOME",C.cyan,page=="HOME");btn("dial",15,y+2,9,2,"DIAL",C.orange,page=="DIAL");btn("iris",26,y+2,9,2,"IRIS",C.yellow);btn("disc",37,y+2,12,2,"DISCONNECT",C.red);btn("diag",51,y+2,12,2,"DIAGNOSTIC",C.cyan,page=="DIAG");btn("log",65,y+2,9,2,"LOG",C.blue,page=="LOG") end
local function dialPage() panel(2,7,W-3,H-14,"DIALING CONSOLE",C.orange);tx(5,9,"DESTINATION",C.muted);V.fill(18,8,30,3,C.metal2);tx(20,9,target=="" and "ENTER 7/9 SYMBOL ADDRESS" or target,C.cyan,C.metal2);btn("clear",W-20,8,7,3,"CLEAR",C.red);btn("go",W-12,8,8,3,"DIAL",C.green);local chars="1234567890ABCDEFGHIJKLMNOPQRSTUVWXYZ";for i=1,#chars do local col=(i-1)%10;local row=math.floor((i-1)/10);btn("k"..i,5+col*7,14+row*2,6,1,chars:sub(i,i),C.blue) end;tx(5,H-8,"SGCraft accepts 7 or 9 symbols; hyphens are optional.",C.muted) end
local function diag(d) panel(2,7,W-3,H-14,"HARDWARE / API DIAGNOSTIC",C.cyan);local function q(y,n,ok,s) tx(6,y,ok and "[ OK ]" or "[FAIL]",ok and C.green or C.red);tx(14,y,n,C.white);tx(36,y,V.fit(s,W-39),ok and C.muted or C.red) end;q(10,"COMPONENT BUS",#gates>0,"stargate x"..#gates);q(12,"STATE API",d.ok,d.ok and d.state or d.error);q(14,"LOCAL ADDRESS",d.localOK,d.localOK and (d.localAddress~="" and d.localAddress or "empty") or d.localError);q(16,"REMOTE ADDRESS",d.remoteOK,d.remoteOK and (d.remoteAddress~="" and d.remoteAddress or "not connected") or d.remoteError);q(18,"ENERGY API",d.energyOK,d.energyOK and string.format("%.1f SEU",d.energy) or d.energyError);q(20,"IRIS API",d.irisOK,d.irisOK and d.iris or d.irisError);tx(6,23,"Interface belongs under the bottom row of the Stargate ring.",C.yellow) end
local function logPage() panel(2,7,W-3,H-14,"SYSTEM EVENT LOG",C.cyan);for i,s in ipairs(logs) do tx(5,9+i-1,V.fit(s,W-9),C.muted) end end
local function render() buttons={};local d=read();header(d);if page=="HOME" then local lw=math.floor(W*.55);panel(2,7,lw,H-14,"STARGATE / PHYSICAL VIEW",C.cyan);V.gate(3,8,lw-2,H-16,d,t);bus(lw+2,7,W-lw-4,10);telemetry(lw+2,18,W-lw-4,H-25,d);controls(H-7) elseif page=="DIAL" then dialPage();controls(H-7) elseif page=="DIAG" then diag(d);controls(H-7) else logPage();controls(H-7) end end
local function act(id)
 if not id then return end;if id=="home" then page="HOME" elseif id=="dial" then page="DIAL" elseif id=="diag" then page="DIAG" elseif id=="log" then page="LOG" elseif id=="scan" then scan() elseif id=="iris" then iris() elseif id=="disc" then disconnect() elseif id=="clear" then target="" elseif id=="go" then dial(target) else local n=id:match("^g(%d+)$");if n then sel=tonumber(n) else local k=id:match("^k(%d+)$");if k then local chars="1234567890ABCDEFGHIJKLMNOPQRSTUVWXYZ";target=target..chars:sub(tonumber(k),tonumber(k)) end end end end
load();scan();local timer=event.timer(.12,function() t=t+.12;render() end,math.huge);render()
while true do local e={event.pull(.25)};if e[1]=="touch" then act(hit(e[3],e[4])) elseif e[1]=="key_down" then local ch=e[4];if page=="DIAL" then if ch==8 or ch==127 then target=target:sub(1,-2) elseif ch==13 then dial(target) elseif ch>=32 and ch<=126 then local c=string.char(ch):upper();if c:match("[%w]") then target=target..c end end elseif e[1]=="sgStargateStateChange" or e[1]=="sgChevronEngaged" or e[1]=="sgIrisStateChange" or e[1]=="sgDialIn" or e[1]=="sgDialOut" then notice="EVENT / "..e[1] elseif e[1]=="interrupted" then break end;if computer.uptime()-last>3 then scan() end end
if timer then pcall(event.cancel,timer) end;V.fill(1,1,W,H,C.black)
